[project]
name = "infobip-mcp-openai-agents-sdk-demo"
version = "0.1.0"
description = "A demo project using Infobip MCP with OpenAI agends SDK."
readme = "README.md"
requires-python = ">=3.12.9"
dependencies = [
    "openai-agents>=0.3.1",
    "python-dotenv>=1.1.1"
]
